const productsHome = [
  {
    name: "X-Shot Lanzadardos Chaos 12 Dardos-Bola ",
    SKU: "ZU36499",
    sale: 0,
    price: 20795.0,
    imgUrl: "images/tienda/pistola-1.jpg",
    cantidad: 1,
  },
  {
    name: "Perrito de Peluche con Aerógrafo ",
    SKU: "CTOFG249",
    sale: 0,
    price: 24995.0,
    imgUrl: "images/tienda/perrito-1.jpg",
    imgUrl2: "images/tienda/perrito-2.jpg",
    cantidad: 1,
  },
  {
    name: "Dinosaurio T-Rex de Peluche con Aerógrafo Style 4 Ever Con 100 Plantillas",
    SKU: "CTOFG243",
    sale: 0,
    price: 24995.0,
    imgUrl: "images/tienda/t-rex-1.jpg",
    cantidad: 1,
  },
  {
    name: "Minis Princesas Disney Comics Sorpresa Serie2 ",
    SKU: "HBE6279",
    sale: 4795,
    price: 6395,
    imgUrl: "images/tienda/minisprincesas.jpg",
    imgUrl2: "images/tienda/minisprincesas2.jpg",
    cantidad: 1,
  },
  {
    name: "X-Shot Lanzadardos Chaos 12 Dardos-Bola ",
    SKU: "ZU36499",
    sale: 0,
    price: 20795.0,
    imgUrl: "images/tienda/pistola-1.jpg",
    cantidad: 1,
  },
];

// bebes tienda
const tiendaBebes = [
  {
    name: "Ríe Y Aprende Mi Primer Mascota Digital ",
    SKU: "MTHHC51",
    sale: 0,
    price: 9795.0,
    imgUrl: "images/categorias/bebes/mascotaDigital-1.jpg",
    imgUrl2: "images/categorias/bebes/mascotaDigital-2.jpg",
  },
  {
    name: "Mordedera Honguito",
    SKU: "MTHBP46",
    sale: 0,
    price: 8945.0,
    imgUrl: "images/categorias/bebes/mordederahonguito-1.jpg",
    imgUrl2: "images/categorias/bebes/mordederahonguito-2.jpg",
  },
  {
    name: "Llavero Juega y Aprende",
    SKU: "MTGRF17",
    sale: 0,
    price: 11495.0,
    imgUrl: "images/categorias/bebes/LlaveroJuegayAprende-1.jpg",
    imgUrl2: "images/categorias/bebes/LlaveroJuegayAprende-2.jpg",
  },
  {
    name: "Ríe Y Aprende Control Remoto De Perrito",
    SKU: "MTDLH81",
    sale: 0,
    price: 9795.0,
    imgUrl: "images/categorias/bebes/MTDLH81-1.jpg",
    imgUrl2: "images/categorias/bebes/MTDLH81-2.jpg",
  },
  {
    name: "Tren con Animalitos Luz/ Sonidos ",
    SKU: "NS69085",
    sale: 0,
    price: 19995.0,
    imgUrl: "images/categorias/bebes/NS69085-1.jpg",
    imgUrl2: "images/categorias/bebes/NS69085-2.jpg",
  },
  {
    name: "Tablet De Aprendizaje Crece Conmigo Azul ",
    SKU: "MTCMC69",
    sale: 0,
    price: 17495.0,
    imgUrl: "images/categorias/bebes/MTCMC69-1.jpg",
    imgUrl2: "images/categorias/bebes/MTCMC69-2.jpg",
  },
  {
    name: "Adopta un Perrito ",
    SKU: "NS69089F",
    sale: 0,
    price: 11995.0,
    imgUrl: "images/categorias/bebes/NS69089F-1.jpg",
  },
  {
    name: "Tablet con Sonidos para bebe ",
    SKU: "NS69093",
    sale: 0,
    price: 11995.0,
    imgUrl: "images/categorias/bebes/NS69093-1.jpg",
    imgUrl2: "images/categorias/bebes/NS69093-2.jpg",
  },
  {
    name: " Carro de Policía de Chase Paw Patrol la Película ",
    SKU: "MTGYJ00",
    sale: 0,
    price: 15265.0,
    imgUrl: "images/categorias/bebes/MTGYJ00-1.jpg",
    imgUrl2: "images/categorias/bebes/MTGYJ00-2.jpg",
  },
];

const accesoriosBebe = [
  {
    name: "Manta de Microfibra para Bebé Amapolas 30x40 ",
    SKU: "FDPR3459",
    sale: 0,
    price: 4795.0,
    imgUrl: "images/categorias/bebes/FDPR3459-1.jpg",
  },
  {
    name: "Mameluco Sin Mangas Set de 5 Azul 3-6m",
    SKU: "BV37020MB",
    sale: 0,
    price: 8945.0,
    imgUrl: "images/categorias/bebes/BV37020MB-1.jpg",
  },
  {
    name: "Toallas con Capucha Set de 3 Azul 76x76cm",
    SKU: "BV05130B",
    sale: 0,
    price: 13495.0,
    imgUrl: "images/categorias/bebes/BV05130B-1.jpg",
  },
  {
    name: "Beberito 9 Oz / 270 Ml",
    SKU: "DRTC91023",
    sale: 0,
    price: 5995.0,
    imgUrl: "images/categorias/bebes/DRTC91023-1.jpg",
  },
  {
    name: "Chupon de Transicion con Asas y Boquilla 9 Oz Rosa",
    SKU: "DRWB91002",
    sale: 0,
    price: 8995.0,
    imgUrl: "images/categorias/bebes/DRWB91002-1.jpg",
  },
];

const productosDestacados = [{}];
